run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - bodyclose
    - unconvert
    - unparam
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  gofmt:
    simplify: true

  revive:
    confidence: 0.8

  gosec:
    excludes:
      - G104 # Audit errors not checked
    severity: medium

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
